name: Build MikaKernel


on:
  workflow_dispatch:

 
jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        run: |
          echo "ANYKERNEL_SOURCE=$(cat config.env | grep -w "ANYKERNEL_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          echo "ANYKERNEL_SOURCE_BRANCH=$(cat config.env | grep -w "ANYKERNEL_SOURCE_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
          sudo apt-get update -y
          sudo apt-get install -y ccache lzop cpio bzip2 zip flex bison gperf
          
      - name: Pull toolchain and kernel
        run: |
          mkdir android-kernel && cd android-kernel
          curl https://storage.googleapis.com/git-repo-downloads/repo > repo && chmod +x ./repo
          ./repo init -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10-2023-04
          ./repo sync -c -j$(($(getconf _NPROCESSORS_ONLN) * 2))
          echo "检查代码完整性"
          ./repo sync && ls
          echo "5.10.168更换为5.10.66"
          rm -rf common
          git clone --depth=1 https://github.com/aosp-mirror/kernel_common -b deprecated/android12-5.10-2022-01 --single-branch common
          echo "修复完毕" && ls
          
      - name: Build kernel
        run: |
          echo "开始构建内核" 
          cd android-kernel && ls
          if [[ -f build/build.sh ]];then
            LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh -j$(($(getconf _NPROCESSORS_ONLN) * 2))
          fi
          
      - name: Package kernel
        run: |
          git clone --depth=1 ${{ env.ANYKERNEL_SOURCE }} -b ${{ env.ANYKERNEL_SOURCE_BRANCH }} AnyKernel3 && rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md
          if [[ -f android-kernel/out/android12-5.10/common/arch/arm64/boot/Image.gz-dtb ]]; then
            echo "压缩格式：Image.gz-dtb" && cp android-kernel/out/android12-5.10/common/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb
          elif [[ -f android-kernel/out/android12-5.10/common/arch/arm64/boot/Image-dtb ]]; then
            echo "压缩格式：Image-dtb" && cp android-kernel/out/android12-5.10/common/arch/arm64/boot/Image-dtb AnyKernel3/Image-dtb
          elif [[ -f android-kernel/out/android12-5.10/common/arch/arm64/boot/Image.gz ]]; then
            echo "压缩格式：Image.gz" && cp android-kernel/out/android12-5.10/common/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
          elif [[ -f android-kernel/out/android12-5.10/common/arch/arm64/boot/Image ]]; then
            echo "压缩格式：Image" && cp android-kernel/out/android12-5.10/common/arch/arm64/boot/Image AnyKernel3/Image
          fi
          if [ -f android-kernel/out/android12-5.10/common/arch/arm64/boot/dtbo.img ]; then
            cp android-kernel/out/android12-5.10/common/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
          fi
          rm -rf android-kernel/
          ls

      - name: Upload kernel to artifact
        uses: actions/upload-artifact@v3
        with:
          name: gki-android12-5.10-test
          path: AnyKernel3/*
